# Generated by Django 2.2 on 2022-03-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Blogger Name')),
                ('title', models.CharField(max_length=300, verbose_name='Blog Title')),
            ],
        ),
    ]
